name: demnaa_front
description: "Demnaa flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_map: ^6.0.1
  # geolocator: ^11.0.0
  latlong2: ^0.9.0
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/demna_icone.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/demnaa_header.png
    - assets/images/demna_icone.png
    - assets/images/demnaa_icone_user.png
    - assets/images/demnaa_livraison_moto.png
    - assets/images/demna_moto_taxi.png
    - assets/images/demnaa_moto_sante.png