name: demnaa_front
description: "Demnaa flutter"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

  
  permission_handler: ^11.1.0
  #geolocator: ^10.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

